### ISSUE TITLE
感谢开源，可以出个使用说明吗？

### ISSUE THREAD

**Issue by skeras** [LittleSource/wechat-live-barrage-tool#1]
感谢作者的开源，环境安装好了，连接self.ws = create_connection("ws://127.0.0.1:5798")这个ws报错，是少了啥东东吗？

**Comment by LittleSource** [comment]
这是需要连接websocket 服务器去上报获取到数据，你不需要上报可以自己注释掉 ws 相关的代码
________________________________
发件人: skeras ***@***.***>
发送时间: Wednesday, May 31, 2023 6:25:44 PM
收件人: LittleSource/wechat-live-barrage-tool ***@***.***>
抄送: Subscribed ***@***.***>
主题: [LittleSource/wechat-live-barrage-tool] 感谢开源，可以出个使用说明吗？ (Issue #1)


感谢作者的开源，环境安装好了，连接self.ws = create_connection("ws://127.0.0.1:5798")这个ws报错，是少了啥东东吗？

―

**Comment by skeras** [comment]
感谢回复，这个错误报权限不足，用管理员权限执行py启动也不行，是什么原因？

![image](https://github.com/LittleSource/wechat-live-barrage-tool/assets/29603361/8deab140-430e-48b5-b6a9-a72a89b4ea59)

![image](https://github.com/LittleSource/wechat-live-barrage-tool/assets/29603361/938c0669-dcc9-44d4-b49c-ff2472e0b531)

**Comment by LittleSource** [comment]
可能是未打开微信直播工具或权限不足
